name = "SMoReBase"
uuid = "58e05929-dfd9-4064-9239-8dd6d82f606d"
authors = ["Daniel Bergman <danielrbergman@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
